<a href="https://colab.research.google.com/github/kowoonho/machine-learning/blob/main/Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [26]:
torch.manual_seed(1)
#파이썬 코드를 재실행해도 같은 결과가 나오도록 랜덤 시드를 1로 고정합니다.

In [27]:
x_train = torch.FloatTensor([[1],[2],[3]])
y_train = torch.FloatTensor([[2],[4],[6]])
print(x_train)
print(x_train.shape)

tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])


In [28]:
W = torch.zeros(1, requires_grad = True)
#가중치 W를 0으로 초기화합니다.
print(W)

tensor([0.], requires_grad=True)


In [29]:
b = torch.zeros(1, requires_grad=True)
#bias 또한 0으로 초기화합니다. 
# requires_grad = True인자가 주어진 것은 학습을 통해 계속 변경되는 변수임을 의미
print(b)

tensor([0.], requires_grad=True)


In [30]:
# 직선의 방정식에 해당하는 가설을 선언합니다.
hypothesis = x_train * W + b 
print(hypothesis)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


In [31]:
# 선형회귀의 비용함수에 해당하는 평균제곱 오차를 선언합니다.
cost = torch.mean((hypothesis - y_train) ** 2)
print(cost)

tensor(18.6667, grad_fn=<MeanBackward0>)


In [32]:
# SGD는 경사하강법의 일종이고, lr은 learning rate를 의미합니다.
optimizer = optim.SGD([W, b], lr = 0.01)

In [33]:
nb_epochs = 2000
for epoch in range(nb_epochs + 1):
  hypothesis = x_train * W + b
  cost = torch.mean((hypothesis - y_train) ** 2)

  
  optimizer.zero_grad() #미분을 통해 얻은 기울기를 0으로 초기화
  cost.backward() # W, b에 대한 기울기 계산
  optimizer.step() # 계산된 기울기로 W값 업데이트


  if epoch % 100 == 0:
    print('Epoch {:4d}/{} W: {:.3f}, b: {:.3f} Cost: {:.6f}'.format(
        epoch, nb_epochs, W.item(), b.item(), cost.item()
    ))

Epoch    0/2000 W: 0.187, b: 0.080 Cost: 18.666666
Epoch  100/2000 W: 1.746, b: 0.578 Cost: 0.048171
Epoch  200/2000 W: 1.800, b: 0.454 Cost: 0.029767
Epoch  300/2000 W: 1.843, b: 0.357 Cost: 0.018394
Epoch  400/2000 W: 1.876, b: 0.281 Cost: 0.011366
Epoch  500/2000 W: 1.903, b: 0.221 Cost: 0.007024
Epoch  600/2000 W: 1.924, b: 0.174 Cost: 0.004340
Epoch  700/2000 W: 1.940, b: 0.136 Cost: 0.002682
Epoch  800/2000 W: 1.953, b: 0.107 Cost: 0.001657
Epoch  900/2000 W: 1.963, b: 0.084 Cost: 0.001024
Epoch 1000/2000 W: 1.971, b: 0.066 Cost: 0.000633
Epoch 1100/2000 W: 1.977, b: 0.052 Cost: 0.000391
Epoch 1200/2000 W: 1.982, b: 0.041 Cost: 0.000242
Epoch 1300/2000 W: 1.986, b: 0.032 Cost: 0.000149
Epoch 1400/2000 W: 1.989, b: 0.025 Cost: 0.000092
Epoch 1500/2000 W: 1.991, b: 0.020 Cost: 0.000057
Epoch 1600/2000 W: 1.993, b: 0.016 Cost: 0.000035
Epoch 1700/2000 W: 1.995, b: 0.012 Cost: 0.000022
Epoch 1800/2000 W: 1.996, b: 0.010 Cost: 0.000013
Epoch 1900/2000 W: 1.997, b: 0.008 Cost: 0.000008

In [33]:
## "pytoch로 시작하는 딥러닝 입문"을 참고하여 쓴 코드입니다.
## https://wikidocs.net/53560